/**
 * 🤖 AGENT API ROUTES
 * 
 * Express routes for Missout Agent endpoints
 * Exposes agent functionality for monitoring and demonstration
 */

import { Router, Request, Response } from 'express';
import { getMissoutAgent } from './MissoutAgent';
import { logger } from '../logger';

const router = Router();

/**
 * GET /api/agent/status
 * Get agent status and metrics
 */
router.get('/status', async (req: Request, res: Response) => {
  try {
    const agent = getMissoutAgent();
    const status = agent.getStatus();
    
    res.json({
      success: true,
      data: status,
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error getting agent status', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * GET /api/agent/analytics
 * Get real-time analytics and insights
 */
router.get('/analytics', async (req: Request, res: Response) => {
  try {
    const agent = getMissoutAgent();
    const analytics = await agent.getAnalytics();
    
    res.json({
      success: true,
      data: analytics,
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error getting analytics', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * GET /api/agent/security
 * Get security report
 */
router.get('/security', async (req: Request, res: Response) => {
  try {
    const agent = getMissoutAgent();
    const report = await agent.getSecurityReport();
    
    res.json({
      success: true,
      data: report,
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error getting security report', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * POST /api/agent/action
 * Execute autonomous action (for demonstration)
 */
router.post('/action', async (req: Request, res: Response) => {
  try {
    const { action, params } = req.body;
    
    if (!action) {
      return res.status(400).json({
        success: false,
        error: 'Action parameter required',
      });
    }
    
    const agent = getMissoutAgent();
    const result = await agent.executeAutonomousAction(action, params);
    
    res.json({
      success: true,
      data: result,
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error executing action', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * GET /api/agent/integrations
 * Get integration hub status
 */
router.get('/integrations', async (req: Request, res: Response) => {
  try {
    const agent = getMissoutAgent();
    const status = agent.getStatus();
    
    res.json({
      success: true,
      data: status.subAgents.integrationHub,
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error getting integrations', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * POST /api/agent/wallet-reputation
 * Check wallet reputation via BlockScore
 */
router.post('/wallet-reputation', async (req: Request, res: Response) => {
  try {
    const { address } = req.body;
    
    if (!address) {
      return res.status(400).json({
        success: false,
        error: 'Wallet address required',
      });
    }
    
    const agent = getMissoutAgent();
    const status = agent.getStatus();
    
    // Access IntegrationHub through agent
    // For now return placeholder - would integrate with actual BlockScore API
    
    res.json({
      success: true,
      data: {
        address,
        score: 75,
        tier: 'medium',
        message: 'BlockScore integration ready',
      },
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error checking wallet reputation', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * GET /api/agent/pools/insights
 * Get AI-powered pool insights
 */
router.get('/pools/insights', async (req: Request, res: Response) => {
  try {
    const agent = getMissoutAgent();
    const status = agent.getStatus();
    
    // Get pool insights from PoolOrchestrator
    const poolOrchestrator = status.subAgents.poolOrchestrator;
    
    res.json({
      success: true,
      data: {
        status: poolOrchestrator,
        message: 'Pool insights generated by autonomous agent',
      },
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error getting pool insights', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * GET /api/agent/dashboard
 * Get complete dashboard data
 */
router.get('/dashboard', async (req: Request, res: Response) => {
  try {
    const agent = getMissoutAgent();
    const status = agent.getStatus();
    const analytics = await agent.getAnalytics();
    const security = await agent.getSecurityReport();
    
    res.json({
      success: true,
      data: {
        agent: status,
        analytics,
        security,
        timestamp: new Date(),
      },
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error getting dashboard', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

/**
 * POST /api/agent/analyze-token
 * Analyze token safety using Rust analyzer
 */
router.post('/analyze-token', async (req: Request, res: Response) => {
  try {
    const { mintAddress } = req.body;
    
    if (!mintAddress) {
      return res.status(400).json({
        success: false,
        error: 'mintAddress is required',
      });
    }
    
    const agent = getMissoutAgent();
    const analysis = await agent.analyzeTokenSafety(mintAddress);
    
    res.json({
      success: true,
      data: analysis,
    });
  } catch (error: any) {
    logger.error('[AgentRoutes] Error analyzing token', error);
    res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

export default router;
