use anchor_lang::prelude::*;

#[error_code]
pub enum ErrorCode {
    #[msg("Pool has expired")] PoolExpired,
    #[msg("Pool not expired")] PoolNotExpired,
    #[msg("Pool not empty")] PoolNotEmpty,
    #[msg("Not creator")] NotCreator,
    #[msg("Not developer")] NotDeveloper,
    #[msg("Unauthorized")] Unauthorized,
    #[msg("Already participated")] AlreadyParticipated,
    #[msg("Maximum participants reached")] MaxParticipantsReached,
    #[msg("Pool is closed")] PoolClosed,
    #[msg("Overflow")] Overflow,
    #[msg("Invalid winner account")] InvalidWinnerAccount,
    #[msg("Invalid participant token")] InvalidParticipantToken,
    #[msg("Invalid mint")] InvalidMint,
    #[msg("Mint has mint authority")] MintHasMintAuthority,
    #[msg("Mint has freeze authority")] MintHasFreezeAuthority,
    #[msg("Invalid decimals")] InvalidDecimals,
    #[msg("Excessive fees")] ExcessiveFees,
    #[msg("Invalid participant count")] InvalidParticipantCount,
    #[msg("Invalid randomness account")] InvalidRandomnessAccount,
    #[msg("Randomness not resolved")] RandomnessNotResolved,
    #[msg("No participants")] NoParticipants,
    #[msg("Invalid pool status")] InvalidPoolStatus,
    #[msg("Randomness already set")] RandomnessAlreadySet,
    #[msg("Cannot decrease lock duration")] CannotDecreaseLockDuration,
    #[msg("Randomness not committed")] RandomnessNotCommitted,
    #[msg("Randomness not revealed")] RandomnessNotRevealed,
    #[msg("Invalid randomness")] InvalidRandomness,
    #[msg("Too many participants")] TooManyParticipants,
    #[msg("Invalid participant range")] InvalidParticipantRange,
    #[msg("Invalid amount")] InvalidAmount,
    #[msg("Invalid lock duration")] InvalidLockDuration,
    #[msg("Pool is still locked")] PoolStillLocked,
    #[msg("Invalid participants PDA")] InvalidParticipantsPda,
    #[msg("Insufficient funds for burn")] InsufficientFundsForBurn,
    #[msg("Invalid token program")] InvalidTokenProgram,
    #[msg("Zero supply")] ZeroSupply,
    #[msg("Spoofed donation")] SpoofedDonation,
    #[msg("Invalid winner pubkey")] InvalidWinnerPubkey,
    #[msg("Invalid winner token owner")] InvalidWinnerTokenOwner,
    #[msg("Mint has unsupported extensions")] ForbiddenExtension,
    #[msg("ATA has delegate")] HasDelegate,
    #[msg("ATA has close authority")] HasCloseAuthority,
    #[msg("Pool is paused")] Paused,
    #[msg("Config mismatch")] ConfigMismatch,
    #[msg("Account is frozen")] FrozenAccount,
    #[msg("Insufficient funds")] InsufficientFunds,
    #[msg("Uninitialized account")] UninitializedAccount,
    #[msg("Randomness expired")] RandomnessExpired,
    #[msg("Account already initialized")] AlreadyInitialized,
    #[msg("Pool unavailable for join")] PoolUnavailableForJoin,
    #[msg("Cannot join because lock has started")] PoolLockedForJoin,
    #[msg("Dust not allowed")] DustNotAllowed,
    #[msg("Pool has already unlocked - joining closed")] JoinClosedAfterUnlock,
    #[msg("Donations are closed after unlocking")] DonateClosedAfterUnlock,
    #[msg("Too early for emergency finalize")] TooEarlyForEmergency,
    #[msg("Not participant")] NotParticipant,
    #[msg("Pool already ended")] AlreadyEnded,
    #[msg("Cannot change lock duration after participants joined")] CannotChangeAfterJoins,
    #[msg("No winner selected")] NoWinnerSelected,
    // Token-2022 Extension Security Errors
    #[msg("Transfer fee extension is not allowed - would modify transfer amounts")] ForbiddenTransferFee,
    #[msg("Transfer hook extension is not allowed - arbitrary code execution risk")] ForbiddenTransferHook,
    #[msg("Confidential transfer extension is not allowed - hidden balances break accounting")] ForbiddenConfidentialTransfer,
    #[msg("Non-transferable tokens are not allowed - lottery requires transferable tokens")] ForbiddenNonTransferable,
    #[msg("Interest bearing extension is not allowed - automatic balance changes break payouts")] ForbiddenInterestBearing,
    #[msg("Permanent delegate extension is not allowed - unauthorized control risk")] ForbiddenPermanentDelegate,
    #[msg("Mint close authority must be disabled - mint could be closed")] ForbiddenMintCloseAuthority,
    #[msg("Default account state must be Initialized - frozen accounts cannot participate")] ForbiddenDefaultAccountState,
    // 🔒 Reentrancy Protection
    #[msg("Pool is currently processing another operation - reentrancy blocked")] PoolProcessing,
    // 🔒 Pool token validation
    #[msg("Pool token account mismatch - provided token doesn't match stored")] PoolTokenMismatch,
}
